"""Render a Report to Markdown."""

from __future__ import annotations

from penumbra.types import Citation, PrivacyLevel, Report, ResearchStep, SourcePage


def render_markdown(
    *,
    query: str,
    summary: str,
    plan: list[ResearchStep],
    sources: list[SourcePage],
    citations: list[Citation],
    privacy_level: PrivacyLevel,
    duration_seconds: float,
) -> str:
    """Compose the final Markdown report."""
    parts: list[str] = []
    parts.append(f"# Research: {query.strip()}\n")
    parts.append(
        f"> *Privacy level:* **{privacy_level.name.lower()}** · "
        f"*Sources:* {len(sources)} · "
        f"*Citations:* {len(citations)} · "
        f"*Duration:* {duration_seconds:.1f}s\n"
    )

    parts.append("## Summary\n")
    parts.append(summary.strip() + "\n")

    if citations:
        parts.append("## Key Findings\n")
        for i, c in enumerate(citations, start=1):
            marker = "✓✓" if c.cross_verified else "•"
            conf = f"{c.confidence:.0%}"
            parts.append(f"{i}. {marker} **[{conf}]** {c.claim}")
            for url in c.source_urls:
                parts.append(f"   - {url}")
            parts.append("")

    if plan:
        parts.append("## Research Plan\n")
        for step in plan:
            tag = " 🔒" if step.sensitive else ""
            parts.append(f"- **{step.subquery}**{tag}")
            if step.rationale:
                parts.append(f"  *{step.rationale}*")
        parts.append("")

    if sources:
        parts.append("## Sources\n")
        for i, s in enumerate(sources, start=1):
            via = " · via Tor" if s.via_tor else ""
            parts.append(f"{i}. [{s.title or s.domain}]({s.url}){via}")
        parts.append("")

    parts.append("---\n")
    parts.append("*Generated by [Penumbra](https://github.com/Brankss/Penumbra) — privacy-native research agent.*\n")
    return "\n".join(parts)
